# this is a basic example  of a workflow to deploy services on kubernetes
# it is not meant to be used in production

name: Deploy Services

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to deploy'
        required: true

jobs:
  deploy:
    name: Deploy Services to Kubernetes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/${{ inputs.service }}
    steps:
      - uses: actions/checkout@v2
      - name: build and push docker image
        run: |
          make build
          make push
      - name: deploy
        run: make deploy 

       