# this is a basic example  of a workflow to deploy services regardless the infra (k8s/ecs/...)
# it is not meant to be used in production

name: Deploy Services

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to deploy'
        required: true
      project:
        description: 'Project to deploy'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy Services to Kubernetes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/${{ inputs.service }}
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: make deploy PROJ=${{ inputs.project }}